require_relative '../../urls'

module DaVinciDTRTestKit
  class DTRQuestionnairePackageRequestTest < Inferno::Test
    include URLs

    id :dtr_questionnaire_package_request
    title 'Invoke the DTR Questionnaire Package operation'
    description %(
      Inferno will wait for a DTR questionnaire package request from the client. Upon receipt, Inferno will generate and
      send a response.
    )
    input :access_token

    run do
      wait(
        identifier: access_token,
        message: %(
          Invoke the DTR Questionnaire Package operation by sending a POST request to

          `#{questionnaire_package_url}`

          A questionnaire package generated by Inferno will be returned.

          Inferno will wait for the client to complete Questionnaire pre-population. The client should make FHIR GET
          requests using service base path:

          `#{fhir_base_url}`

          When the DTR application has finished loading the Questionnaire,
          [Click here](#{resume_pass_url}?token=#{access_token}) to continue.
        )
      )
    end
  end
end
