require_relative '../urls'

module DaVinciDTRTestKit
  class AdaptiveQuestionnairePackageRequestTest < Inferno::Test
    include URLs
    title 'Confirm the client completes the DTR Adaptive Questionnaire work flow'
    description %(
      Inferno will wait for a DTR questionnaire package request from the client. Upon receipt, Inferno will generate and
      send a response.
    )
    id :payer_server_questionnaire_package_request
    input :access_token

    run do
      wait(
        identifier: access_token,
        message: %(
          Invoke the DTR Questionnaire Package operation by sending a POST request to

          `#{questionnaire_package_url}`
          
          and Next Question operations by sending POST requests to
          
          `#{next_url}`


          A set of questionnaire packages generated by Inferno will be returned.

          **[click here](#{resume_pass_url}?token=#{access_token})** when the adaptive forms have been completed.
        )
      )
    end
  end
end
