require_relative '../urls'

module DaVinciDTRTestKit
  class AdaptiveNextQuestionnairePackageRequestTest < Inferno::Test
    include URLs
    title 'Client invokes the DTR Next Question operation'
    description %(
      Inferno will wait for a DTR next question request from the client. Upon receipt, Inferno will generate and
      send a response.
    )
    id :payer_server_next_questionnaire_request
    input :access_token

    run do
      wait(
        identifier: access_token,
        message: %(
          Invoke the DTR next question operation by sending a POST request to

          `#{next_url}`

          A questionnaire response generated by Inferno will be returned.
        )
      )
    end
  end
end
