require_relative '../urls'

module DaVinciDTRTestKit
  class AdaptiveFormTest < Inferno::Test
    include URLs
    title 'Confirm the client completes the DTR Adaptive Questionnaire work flow'
    description %(
      Inferno will wait for a DTR questionnaire package request from the client. Upon receipt, Inferno will generate and
      send a response.
    )
    verifies_requirements 'hl7.fhir.us.davinci-dtr_2.0.1@239', 'hl7.fhir.us.davinci-dtr_2.0.1@292'

    id :payer_server_questionnaire_request
    config options: { accepts_multiple_requests: true }

    run do
      skip_if retrieval_method == 'Static', 'Performing only static flow tests - only one flow is required.'
      pass_if !(initial_adaptive_questionnaire_request.nil? || next_question_requests.nil?),
              'Proceeding with manually provided resources.'
      skip_if access_token.nil?, 'Please provide an access token or all request resources as inputs.'
      wait(
        identifier: access_token,
        message: %(
          **Adaptive Form Testing**

          Invoke the DTR Questionnaire Package operation by sending a POST request to

          `#{questionnaire_package_url}`

          and Next Question operations by sending POST requests to

          `#{next_url}`


          A set of questionnaire packages generated by Inferno will be returned. Each of the following tests
          will validate all resources, marking messages in the order they are received.

          **[click here](#{resume_pass_url}?token=#{access_token})** when the adaptive forms have been completed.
        )
      )
    end
  end
end
