require_relative '../urls'
require_relative '../validation_test'
module DaVinciDTRTestKit
  class StaticRFormRequestTest < Inferno::Test
    include URLs
    title 'Validate the questionnaires returned by the payer server'
    description %(
      Inferno will validate questionnaires returned by the payer server.
    )
    id :dtr_v201_payer_static_questionnaire_request_test
    config options: { accepts_multiple_requests: false }

    run do
      skip_if retrieval_method == 'Adaptive', 'Performing only adaptive flow tests - only one flow is required.'
      pass_if !initial_static_questionnaire_request.nil?,
              'Proceeding with manually provided resources.'
      skip_if access_token.nil?, 'Please provide an access token or all request resources as inputs.'
      wait(
        identifier: access_token,
        message: %(
          **Static Form Testing**

          Invoke the DTR Questionnaire Package operation by sending a POST request to

          `#{questionnaire_package_url}`

          A set of questionnaire packages generated by Inferno will be returned. Each of the following tests
          will validate all resources, marking messages in the order they are received.
        )
      )
    end
  end
end
