require 'inferno/dsl/profile_metadata'

module DaVinciDTRTestKit
  # Loads and memoizes the Inferno::DSL::ProfileMetadata generated by Generator into
  # cross_suite/generated/<version>/<profile>/metadata.yml, so test classes don't each
  # need to hand-roll their own file path and loading/memoization boilerplate.
  module GeneratedProfileMetadata
    GENERATED_DIR = File.join(__dir__, 'generated').freeze

    # @param version [String] eg 'v2.2.0'
    # @param profile [String] the generated metadata directory name, eg 'dtr_base_questionnaire'
    # @return [Inferno::DSL::ProfileMetadata]
    def self.for(version, profile)
      cache[[version, profile]] ||=
        Inferno::DSL::ProfileMetadata.from_file(File.join(GENERATED_DIR, version, profile, 'metadata.yml'))
    end

    def self.cache
      @cache ||= {}
    end
  end
end
