require_relative '../../descriptions'
require_relative '../../urls'

module DaVinciDTRTestKit
  class DTRFullEHRQuestionnairePackageRequestTest < Inferno::Test
    include URLs

    id :dtr_full_ehr_qp_request
    title 'Invoke the DTR Questionnaire Package operation'
    description %(
      Inferno will wait for a DTR questionnaire package request from the client. Upon receipt, Inferno will generate and
      send a response.
    )
    verifies_requirements 'hl7.fhir.us.davinci-dtr_2.0.1@165', 'hl7.fhir.us.davinci-dtr_2.0.1@242'

    input :client_id,
          title: 'Client Id',
          type: 'text',
          optional: true,
          locked: true,
          description: INPUT_CLIENT_ID_LOCKED

    run do
      wait(
        identifier: client_id,
        message: %(
          ### Questionnaire Package

          Inferno will wait for the Full EHR to invoke the DTR Questionnaire Package operation by sending a POST
          request to

          `#{questionnaire_package_url}`

          A questionnaire package generated by Inferno will be returned.

          ### Continuing the Tests

          When the DTR application has finished loading the Questionnaire
          [Click here](#{resume_pass_url}?token=#{client_id}) to continue.
        )
      )
    end
  end
end
