require_relative '../../urls'

module DaVinciDTRTestKit
  class DTRFullEHRQuestionnairePackageRequestTest < Inferno::Test
    include URLs

    id :dtr_full_ehr_questionnaire_package_request
    title 'Invoke the DTR Questionnaire Package operation'
    description %(
      Inferno will wait for a DTR questionnaire package request from the client. Upon receipt, Inferno will generate and
      send a response.
    )

    input :access_token,
          description: %(
            `Bearer` token that the client under test will send in the
            `Authorization` header of each HTTP request to Inferno. Inferno
            will look for this value to associate requests with this session.
          )

    run do
      wait(
        identifier: access_token,
        message: %(
          ### Questionnaire Package

          Inferno will wait for the Full EHR to invoke the DTR Questionnaire Package operation by sending a POST
          request to

          `#{questionnaire_package_url}`

          A questionnaire package generated by Inferno will be returned.

          ### Request Identification

          In order to identify requests for this session, Inferno will look for
          an `Authorization` header with value:

          ```
          Bearer #{access_token}
          ```

          ### Continuing the Tests

          When the DTR application has finished loading the Questionnaire
          [Click here](#{resume_pass_url}?token=#{access_token}) to continue.
        )
      )
    end
  end
end
