require_relative '../../urls'

module DaVinciDTRTestKit
  class DTRRespQuestionnairePackageRequestTest < Inferno::Test
    include URLs

    id :dtr_resp_questionnaire_package_request
    title 'Invoke the DTR Questionnaire Package operation'
    description %(
      Inferno will wait for a DTR questionnaire package request from the client. Upon receipt, Inferno will generate and
      send a response.
    )
    input :smart_app_launch, type: 'radio', title: 'SMART App Launch',
                             description: 'How will the DTR SMART App launch?',
                             options: { list_options: [{ label: 'Launch from Inferno', value: 'inferno' },
                                                       { label: 'Launch from EHR', value: 'ehr' }] }
    input :client_id
    input :launch_uri, optional: true, description: 'Required if "Launch from Inferno" is selected'

    run do
      launch_prompt = if smart_app_launch == 'inferno'
                        %(Launch the DTR SMART App from Inferno by right clicking
                          [this link](#{launch_uri}?iss=#{fhir_base_url}&launch=#{launch_uri})
                          and selecting or "Open in new window" or "Open in new tab".)
                      else
                        %(Launch the SMART App from your EHR.)
                      end
      inferno_prompt_cont = %(As the DTR app steps through the launch steps, Inferno will wait and respond to the app's
                              requests for SMART configuration, authorization and access token.)
      wait(
        identifier: client_id,
        message: %(
                   ### SMART App Launch

                   #{launch_prompt}

                   #{inferno_prompt_cont if smart_app_launch == 'inferno'}

                   Then, Inferno will expect the SMART App to invoke the DTR Questionnaire Package operation by sending
                   a POST request to

                   `#{questionnaire_package_url}`

                   A questionnaire package generated by Inferno will be returned.

                   ### Pre-population

                   Inferno will then wait for the client to complete Questionnaire pre-population. The client should
                   make FHIR GET requests using service base path:

                   `#{fhir_base_url}`

                   When the DTR application has finished loading the Questionnaire,
                   [Click here](#{resume_pass_url}?client_id=#{client_id}) to continue.
                 )
      )
    end
  end
end
