require_relative '../urls'

module DaVinciDTRTestKit
  class QuestionnairePackageRequestTest < Inferno::Test
    include URLs

    id :dtr_full_ehr_questionnaire_package_request
    title 'EHR invokes the DTR Questionnaire Package operation'
    description %(
      Inferno will wait for a DTR questionnaire package request from the client. Upon receipt, Inferno will generate and
      send a response.
    )
    input :access_token

    run do
      wait(
        identifier: access_token,
        message: %(
          Invoke the DTR Questionnaire Package operation by sending a POST request to

          `#{questionnaire_package_url}`

          A questionnaire package generated by Inferno will be returned.
        )
      )
    end
  end
end
